part of 'package:shader_graph/shader_graph.dart';

/// 输入来自另一个 ShaderBuffer 的输出纹理。
///
/// Input comes from another ShaderBuffer's output texture.
class ShaderBufferInput extends ShaderInput {
  ShaderBufferInput(
    this.buffer, {
    this.usePreviousFrame = false,
    this.wrap = WrapMode.clamp,
    this.filter = FilterMode.linear,
  });

  final ShaderBuffer buffer;
  final bool usePreviousFrame;
  @override
  final WrapMode wrap;

  @override
  final FilterMode filter;

  /// 对于反馈输入，选择使用上一帧的输出纹理。
  ///
  /// For feedback input, choose to use the output texture from the previous frame.
  @override
  ui.Image? resolve() {
    return usePreviousFrame ? buffer._prevOutput : buffer._output;
  }
}

/// 输入来自 Flutter ImageProvider。
///
/// Input comes from a Flutter ImageProvider.
class ImageProviderInput extends ShaderInput {
  ImageProviderInput(
      {required this.provider,
      this.wrap = WrapMode.clamp,
      this.filter = FilterMode.linear});

  final ImageProvider provider;
  ImageStream? _stream;
  ImageStreamListener? _listener;
  ImageInfo? _imageInfo;

  @override
  final WrapMode wrap;

  @override
  final FilterMode filter;

  void _resolveProvider() {
    _stream = provider.resolve(ImageConfiguration.empty);
    _listener = ImageStreamListener(
      (imageInfo, _) {
        _imageInfo?.dispose();
        _imageInfo = imageInfo;
      },
      onError: (Object error, StackTrace? stackTrace) {
        debugPrint('Failed to resolve image provider $provider: $error');
      },
    );
    _stream!.addListener(_listener!);
  }

  @override
  ui.Image? resolve() {
    if (_stream == null) {
      _resolveProvider();
    }
    return _imageInfo?.image;
  }

  @override
  void dispose() {
    final stream = _stream;
    final listener = _listener;
    if (stream != null && listener != null) {
      stream.removeListener(listener);
    }
    _imageInfo?.dispose();
    _imageInfo = null;
    _stream = null;
    _listener = null;
  }
}

/// 输入来自键盘控制器生成的键盘纹理。
///
/// Input comes from a keyboard texture generated by KeyboardController.
class KeyboardInput extends ShaderInput {
  KeyboardInput({this.wrap = WrapMode.clamp, this.filter = FilterMode.linear});

  @override
  final WrapMode wrap;

  @override
  final FilterMode filter;

  ui.Image? Function()? imageProvider;

  @override
  ui.Image? resolve() => imageProvider?.call();
}

/// 输入来自一个 Widget 的渲染结果。
///
/// Input comes from the rendering result of a Widget.
class WidgetInput extends ShaderInput {
  WidgetInput({
    required this.widget,
    this.wrap = WrapMode.clamp,
    this.filter = FilterMode.linear,
  });

  final Widget widget;

  @override
  final WrapMode wrap;

  @override
  final FilterMode filter;

  ui.Image? lastImage;

  @override
  ui.Image? resolve() => lastImage;
}

/// 空输入，会在 `ShaderBuffer,render` 中用默认的 Image 填充
///
/// Empty input, will be filled with a default Image in `ShaderBuffer.render`
class EmptyInput extends ShaderInput {
  EmptyInput({this.wrap = WrapMode.clamp, this.filter = FilterMode.linear});

  @override
  final WrapMode wrap;

  @override
  final FilterMode filter;

  @override
  ui.Image? resolve() => null;
}
