{
  "sksl": {
    "entrypoint": "expansivereactiondiffusionBufferD_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 iResolution;\nuniform float iTime;\nuniform float iFrame;\nuniform vec4 iMouse;\nuniform vec4 iChannelWrap;\nuniform vec4 iChannelFilter;\nuniform vec2 iChannelResolution0;\nuniform vec2 iChannelResolution1;\nuniform vec2 iChannelResolution2;\nuniform vec2 iChannelResolution3;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_flutter_local_mainImage(out vec4 fragColor_1, vec2 fragCoord)\n{\n    vec2 uv = fragCoord / iResolution;\n    vec2 pixelSize = vec2(1.0) / iResolution;\n    float eighth = 0.125;\n    fragColor_1 = vec4(0.0);\n    bool _53 = uv.x > (7.0 * eighth);\n    bool _62;\n    if (_53)\n    {\n        _62 = uv.x < (8.0 * eighth);\n    }\n    else\n    {\n        _62 = _53;\n    }\n    bool _72;\n    if (_62)\n    {\n        _72 = uv.y > (2.0 * eighth);\n    }\n    else\n    {\n        _72 = _62;\n    }\n    bool _81;\n    if (_72)\n    {\n        _81 = uv.y < (3.0 * eighth);\n    }\n    else\n    {\n        _81 = _72;\n    }\n    if (_81)\n    {\n        fragColor_1 = vec4(iMouse.xy / iResolution, iMouse.zw / iResolution);\n    }\n}\n\nvoid FLT_main()\n{\n    float keep = ((((((((((((iFrame + iMouse.x) + iTime) + iResolution.x) + iChannelWrap.x) + iChannelFilter.x) + iChannelResolution0.x) + iChannelResolution0.y) + iChannelResolution1.x) + iChannelResolution1.y) + iChannelResolution2.x) + iChannelResolution2.y) + iChannelResolution3.x) + iChannelResolution3.y;\n    vec2 fragCoord_1 = FLT_flutter_local_FlutterFragCoord();\n    vec2 param_1 = fragCoord_1;\n    vec4 param;\n    FLT_flutter_local_mainImage(param, param_1);\n    fragColor = param;\n    if (keep < (-100000002004087734272.0))\n    {\n        fragColor += vec4(keep);\n    }\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "iResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "iTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "iFrame",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "iMouse",
        "rows": 4,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "iChannelWrap",
        "rows": 4,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "iChannelFilter",
        "rows": 4,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 6,
        "name": "iChannelResolution0",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 7,
        "name": "iChannelResolution1",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 8,
        "name": "iChannelResolution2",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 9,
        "name": "iChannelResolution3",
        "rows": 2,
        "type": 10
      }
    ]
  }
}